version: '3.8'

services:
  mysql1:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: orders
    ports:
      - "3306:3306"
    volumes:
      - mysql1_data:/var/lib/mysql
    restart: always

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always

  myapp:
    image: app:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
    networks:
      - monitoring
    depends_on:
      - mysql1

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command: [ "--config.file=/etc/prometheus/prometheus.yml" ]
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    networks:
      - monitoring

volumes:
  mysql1_data:

networks:
  monitoring:
    driver: bridge