version: '3.8'
services:
  mysql1:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: orders
    ports:
      - "3306:3306"
    volumes:
      - mysql1_data:/var/lib/mysql
    restart: always


  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always

volumes:
  mysql1_data:
