server:
  port: 8081

spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/orders?zeroDateTimeBehavior=convertToNull
    username: root
    password: secret
    pool:
      enabled: true
      max-size: 20
      initial-size: 5
      max-idle-time: 30m
  sql:
    init:
      mode: always
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false

api:
  base-url: http:localhost:8089